### ISSUE TITLE
Beta Release Essentials

### ISSUE THREAD

**Issue by SaifMasoud** [cooperemily02/WeathertoWear#51]
Reference: https://people.cs.umass.edu/~brun/class/2022Fall/CS320/beta/beta.pdf

- [x] Main use cases
  - [x] #44 
  - [x] Viewing the users' items (their closet) #59.
  - [x] Getting Outfit of the day #49 
- [x] Document working and in-progress features, document bugs
- [x] Packaging: Binary/URL & source code
- [x] Testing #43 (unit tests for a major class, integration tests for use cases)
- [x] Update SRS/SDS
- [x] "A description of how you have applied one design pattern or principle..."
- [x] Presentations
